name: Build starters using JUnit
on:
  push:
  pull_request:
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: 'JUnit 5 SNAPSHOT build: Maven'
        run: cd ${GITHUB_WORKSPACE}/junit5-jupiter-starter-maven && ./mvnw test --batch-mode --file pom.xml
